### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by edwintcloud** [team-morpheus/lasagna#13]
- [ ] Bottom Navbar (Recipes, Profile, Search)
- [ ] Search Component
  - [ ] Filter results by dietary restrictions, cuisines, price, cooking skill required, time to make, ingredients
- [ ] Recipes Component (refactor for mobile first)
- [ ] Profile
  - [ ] Upload Avatar
  - [ ] Edit description, skill, and budget
  - [ ] Add favorite cuisines
  - [ ] Dietary Restrictions
- [ ] Add/Update Recipes Modal
  - [ ] Fix mobile display issues for ingredients
  - [ ] Add fields for skill required, price, time required to make
- [ ] PWA features
- [ ] SEO

Future
- [ ] Social Features
  - [ ] User can rate a recipe
  - [ ] User can comment on a recipe
  - [ ] User can view other users' recipes and profile (if shared as public)
  - [ ] Share to facebook, twitter, etc..
- [ ] SSO
  - [ ] Google Sign-In
  - [ ] Registration flow for setting up preferences when using SSO
